// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz1XLgISOL4Ub1yPexdX4M0Ut47165GuE',
    appId: '1:962531189850:web:d2f052a6572f0c7458a463',
    messagingSenderId: '962531189850',
    projectId: 'under-throw-9256a',
    authDomain: 'under-throw-9256a.firebaseapp.com',
    databaseURL: 'https://under-throw-9256a-default-rtdb.firebaseio.com',
    storageBucket: 'under-throw-9256a.firebasestorage.app',
    measurementId: 'G-H7D5428ZBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-7NxntFheinhNfWlntpagEnT58JCjRbU',
    appId: '1:962531189850:android:d7cd9bb8a1fac0c158a463',
    messagingSenderId: '962531189850',
    projectId: 'under-throw-9256a',
    databaseURL: 'https://under-throw-9256a-default-rtdb.firebaseio.com',
    storageBucket: 'under-throw-9256a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgzZ1jPWheEKA4OXGmsNJWkvuX1_fq1Xs',
    appId: '1:962531189850:ios:dcc2f040d637b75d58a463',
    messagingSenderId: '962531189850',
    projectId: 'under-throw-9256a',
    databaseURL: 'https://under-throw-9256a-default-rtdb.firebaseio.com',
    storageBucket: 'under-throw-9256a.firebasestorage.app',
    iosBundleId: 'com.underthrow.flutterToiletApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgzZ1jPWheEKA4OXGmsNJWkvuX1_fq1Xs',
    appId: '1:962531189850:ios:dcc2f040d637b75d58a463',
    messagingSenderId: '962531189850',
    projectId: 'under-throw-9256a',
    databaseURL: 'https://under-throw-9256a-default-rtdb.firebaseio.com',
    storageBucket: 'under-throw-9256a.firebasestorage.app',
    iosBundleId: 'com.underthrow.flutterToiletApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz1XLgISOL4Ub1yPexdX4M0Ut47165GuE',
    appId: '1:962531189850:web:7ccf4a6ca9d3f42b58a463',
    messagingSenderId: '962531189850',
    projectId: 'under-throw-9256a',
    authDomain: 'under-throw-9256a.firebaseapp.com',
    databaseURL: 'https://under-throw-9256a-default-rtdb.firebaseio.com',
    storageBucket: 'under-throw-9256a.firebasestorage.app',
    measurementId: 'G-XH1D1RE923',
  );

}